# Generated by Django 5.1.6 on 2025-02-22 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='VoteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.poll')),
            ],
        ),
        migrations.CreateModel(
            name='UserVoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.poll')),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.voteoption')),
            ],
        ),
    ]
