# Generated by Django 6.0 on 2025-12-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservoteitem',
            name='user_number',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
